// AUTO-GENERATED by scripts/sync-shared.mjs — edit shared/schema.ts instead.
import { z } from "npm:zod@3.23.8";

// AI 생성 결과 검증 스키마 (CLAUDE.md 5-5). INSERT 전 반드시 이 스키마를 통과해야 한다.
export const qLevelSchema = z.enum(["IH", "AL", "AM"]);

export const stimulusSchema = z.object({
  text: z.string().nullable().optional(),
  infoTable: z.record(z.string(), z.unknown()).nullable().optional(),
  scenario: z.string().nullable().optional(),
});

export const modelAnswerSchema = z.object({
  templateId: z.string(),
  slots: z.record(z.string(), z.string()),
  rendered: z.string(),
  wordCount: z.number().int().positive(),
});

export const generatedQuestionSchema = z.object({
  no: z.number().int().min(1).max(11),
  prompt: z.string().min(1),
  prepSec: z.number().int().positive(),
  responseSec: z.number().int().positive(),
  modelAnswer: modelAnswerSchema,
  keyExpressions: z.array(z.string()).default([]),
  raterNotes: z.string().optional(),
  // Ch2(Q3,Q4)는 문항마다 다른 사진을 쓰므로 이미지는 세트가 아닌 문항 단위로 갖는다.
  imageUrl: z.string().url().nullable().optional(),
  imageCredit: z.string().nullable().optional(),
});

export const generatedQuestionSetSchema = z.object({
  chapterId: z.number().int().min(1).max(5),
  difficulty: qLevelSchema,
  topicKey: z.string().min(1),
  stimulus: stimulusSchema,
  questions: z.array(generatedQuestionSchema).min(1),
});

export type GeneratedQuestionSet = z.infer<typeof generatedQuestionSetSchema>;
export type GeneratedQuestion = z.infer<typeof generatedQuestionSchema>;
export type ModelAnswer = z.infer<typeof modelAnswerSchema>;

// 자기채점 체크리스트 (7-4)
export const selfScoreSchema = z.object({
  filledTime: z.boolean(),
  templateStructure: z.boolean(),
  noLongPause: z.boolean(),
  grammarChecked: z.boolean(),
  contentRelevant: z.boolean(),
});
export type SelfScore = z.infer<typeof selfScoreSchema>;

// 단어 수 검증 헬퍼 (11장 작업 규칙)
export function isWordCountValid(templateId: string, wordCount: number, ranges: Record<string, { min: number; max: number }>): boolean {
  const range = ranges[templateId];
  if (!range) return true;
  return wordCount >= range.min && wordCount <= range.max;
}
