// Deno Edge Function은 supabase/functions 밖의 파일을 import하기 어려우므로
// shared/schema.ts, shared/parts.ts를 supabase/functions/_shared/로 복사한다.
// Deno는 bare specifier("zod")를 resolve하지 못하므로 복사하면서 npm: 접두사를 붙인다.
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = dirname(dirname(fileURLToPath(import.meta.url)));
const targetDir = join(root, "supabase", "functions", "_shared");
mkdirSync(targetDir, { recursive: true });

for (const file of ["schema.ts", "parts.ts"]) {
  const src = readFileSync(join(root, "shared", file), "utf8");
  const rewritten = src.replace(/from "zod"/g, 'from "npm:zod@3.23.8"');
  writeFileSync(join(targetDir, file), `// AUTO-GENERATED by scripts/sync-shared.mjs — edit shared/${file} instead.\n${rewritten}`);
  console.log(`synced shared/${file} -> supabase/functions/_shared/${file}`);
}
